### PR TITLE
Change to the SEER Historic Stage algorithm

### LINKED ISSUE #45: Updates for newly ocurring CS codes
Historic Stage needs to be updated annually to account for any new CS codes that had not previously been accounted for.

### PR DESCRIPTION
**Pull request by flynngr**
Fixes #45.

### CODE REVIEW

**Comment by depryf** [comment]
@flynngr the changes look good. I saw a few minor formatting issues in the test file, but that's not a big deal.

One thing though: can you please add an entry for you changes in the CHANGELOG.md file? Just check the VERSION file to know the current version (minus the -SNAPSHOT), and then either add to the section for that version if it already exists, or create a new one if it doesn't. Please use a one-line simple description of our changes, no need to be too exhaustive there. 

Thanks.

**Comment by flynngr** [comment]
@depryf - I changed those and pushed.   Do I do I do a new pull request?

**Comment by depryf** [comment]
Nope, no need of a new pull request. This looks good now and I am merging it. If you need this soon, then let me know and I will make a release of the library; otherwise these changes will be available the next time the library is released.

**Comment by flynngr** [comment]
I think that the next release will be fine.  After 11/1 is best to not alarm the registries during submission -- the effect on their DQPs would be minimal so no need to incorporate.

**Comment by depryf** [comment]
Good. There are a few more issues opened for this library and I would like to resolve some of them before making another release...

**Pull request merged**
