### PR TITLE
#41 - Update poverty linkage algorithm for 2018

### PR DESCRIPTION
**Pull request by howew**

### CODE REVIEW

**Comment by depryf** [comment]
@howew the changes look good. Can you please add an entry in the CHANGELOG.md file? Thanks.

**Comment by howew** [comment]
Sure.  Should I add it under 1.17 or create a 1.18 section?

**Comment by depryf** [comment]
You can check the VERSION file; since it says "1.17-SNAPSHOT", this should go under a "1.17" section (you can add it if it doesn't exist yet).

**Comment by howew** [comment]
OK, this is done.

**Pull request merged**
