### PR TITLE
Site-Specific Surgery codes - 2024 update (#180)

### PR DESCRIPTION
**Pull request by jlorentson**
Please release this branch as a SNAPSHOT before merging.

### CODE REVIEW

**Comment by depryf** [comment]
@jlorentson  can you please an entry in the CHANGELOG file for this work?  Thanks.

**Comment by jlorentson** [comment]
Will do. I found a couple typos; doing a quick pass to find others. I'll add the changelog entry when that's done.

**Comment by jlorentson** [comment]
@depryf ready for review

**Comment by depryf** [comment]
Looking good. I am going to create a snapshot release.

**Comment by jlorentson** [comment]
@depryf I think this can be merged. Thanks again!

**Pull request merged**
